# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: medical.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'medical.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmedical.proto\"J\n\rReportRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x13\n\x0breport_text\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"_\n\x0eReportResponse\x12\x0f\n\x07summary\x18\x01 \x01(\t\x12\x1b\n\x13suggested_diagnoses\x18\x02 \x03(\t\x12\x1f\n\x17recommended_specialists\x18\x03 \x03(\t2J\n\x0fMedicalAnalyzer\x12\x37\n\x14\x41nalyzeMedicalReport\x12\x0e.ReportRequest\x1a\x0f.ReportResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'medical_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REPORTREQUEST']._serialized_start=17
  _globals['_REPORTREQUEST']._serialized_end=91
  _globals['_REPORTRESPONSE']._serialized_start=93
  _globals['_REPORTRESPONSE']._serialized_end=188
  _globals['_MEDICALANALYZER']._serialized_start=190
  _globals['_MEDICALANALYZER']._serialized_end=264
# @@protoc_insertion_point(module_scope)
